<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>in.virit.iot</groupId>
    <artifactId>pi-starter-reactor</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Pi Starter Reactor</name>
    <modules>
        <module>pi-helpers</module>
        <module>pi-helpers-simulation</module>
        <module>example-project</module>
    </modules>
</project>
